/**
 * Islamic Values — Runtime Store
 * ------------------------------------------------------------------
 * Loads config/values.json (generated by `npm run build:values` from the
 * LOCAL dataset only), caches it, and serves read queries:
 *   - value list with counts
 *   - paginated + filtered hadiths for a value (from SQLite, no AI)
 *   - reverse index: hadith id -> value ids (for cross-link tags)
 *   - deterministic "value of the day"
 *   - strong value-name matcher for the search box
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getHadithById } from '../db/database.js';
import { normalizeArabic } from '../db/arabic-utils.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VALUES_PATH = path.resolve(__dirname, '..', '..', 'config', 'values.json');

let docCache = null;      // parsed values.json
let docMtime = 0;         // file mtime for auto-reload
let reverseIndex = null;  // hadithId -> [{valueId, nameAr, nameEn}]
let byIdMap = null;       // valueId -> value

function loadDoc() {
  try {
    const stat = fs.statSync(VALUES_PATH);
    if (docCache && stat.mtimeMs === docMtime) return docCache;
    const raw = fs.readFileSync(VALUES_PATH, 'utf8');
    docCache = JSON.parse(raw);
    docMtime = stat.mtimeMs;
    reverseIndex = new Map();
    byIdMap = new Map();
    for (const v of (docCache.values || [])) {
      byIdMap.set(v.id, v);
      for (const hid of (v.hadithIds || [])) {
        if (!reverseIndex.has(hid)) reverseIndex.set(hid, []);
        reverseIndex.get(hid).push({ id: v.id, nameAr: v.nameAr, nameEn: v.nameEn, accent: v.accent });
      }
    }
    console.log(`[Values] loaded ${byIdMap.size} values from config/values.json`);
    return docCache;
  } catch (err) {
    if (!docCache) {
      console.error('[Values] could not load config/values.json — run `npm run build:values`:', err.message);
      docCache = { schemaVersion: 1, note: '', generatedAt: null, values: [] };
      reverseIndex = new Map();
      byIdMap = new Map();
    }
    return docCache;
  }
}

export function isValuesAvailable() {
  return loadDoc().values.length > 0;
}

/** Public summary list for the gallery. */
export function listValues() {
  const doc = loadDoc();
  return doc.values.map(v => ({
    id: v.id,
    nameAr: v.nameAr,
    nameEn: v.nameEn,
    descAr: v.descAr,
    iconKey: v.iconKey,
    accent: v.accent,
    count: (v.hadithIds || []).length
  }));
}

export function getReferenceNote() {
  return loadDoc().note || '';
}

export function getValueMeta(valueId) {
  const doc = loadDoc();
  return (doc.values.find(v => v.id === valueId)) || null;
}

/**
 * Resolve a value's hadiths from the local dataset with optional
 * filtering (book / narrator / free text) and pagination.
 */
export function getValueHadiths(valueId, { page = 1, limit = 10, book = '', narrator = '', text = '' } = {}) {
  const value = getValueMeta(valueId);
  if (!value) return null;

  const bookFilter = String(book || '').toLowerCase().trim();     // 'bukhari' | 'muslim' | ''
  const narratorFilter = normalizeArabic(String(narrator || '')); // substring, normalized
  const textFilter = normalizeArabic(String(text || ''));

  const all = [];
  for (const hid of (value.hadithIds || [])) {
    const h = getHadithById(hid);
    if (!h) continue; // never fabricate: missing rows are skipped
    all.push({
      id: h.id,
      source: h.source,
      hadithNumber: h.hadith_number,
      arabicNumber: h.arabic_number,
      bookNumber: h.book_number,
      bookName: h.book_name,
      narrator: h.narrator,
      textFull: h.text_full,
      grade: h.grade,
      reference: h.reference
    });
  }

  let filtered = all;
  if (bookFilter) filtered = filtered.filter(h => h.source === bookFilter);
  if (narratorFilter) filtered = filtered.filter(h => normalizeArabic(h.narrator || '').includes(narratorFilter));
  if (textFilter) filtered = filtered.filter(h => normalizeArabic(h.textFull || '').includes(textFilter));

  const pageSize = Math.max(1, Math.min(parseInt(limit, 10) || 10, 50));
  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const pageNum = Math.max(1, Math.min(parseInt(page, 10) || 1, totalPages));
  const start = (pageNum - 1) * pageSize;

  // Distinct narrator options for the filter UI.
  const narrators = [...new Set(all.map(h => h.narrator).filter(Boolean))].sort();

  return {
    value: {
      id: value.id, nameAr: value.nameAr, nameEn: value.nameEn, descAr: value.descAr,
      iconKey: value.iconKey, accent: value.accent, count: (value.hadithIds || []).length,
      note: loadDoc().note
    },
    hadiths: filtered.slice(start, start + pageSize),
    pagination: { page: pageNum, limit: pageSize, total, totalPages },
    filters: { book: bookFilter || null, narrator: narrator || '', text: text || '', narratorOptions: narrators }
  };
}

/** Value tags for a hadith card (cross-links). */
export function getValuesForHadith(hadithId) {
  loadDoc();
  return (reverseIndex && reverseIndex.get(hadithId)) || [];
}

/** True if two hadiths share at least one value (for "related" ranking). */
export function shareValue(idA, idB) {
  loadDoc();
  const a = reverseIndex.get(idA) || [];
  const b = reverseIndex.get(idB) || [];
  const ids = new Set(a.map(v => v.id));
  return b.some(v => ids.has(v.id));
}

/**
 * Deterministic "value of the day" — stable string hash of YYYY-MM-DD.
 */
export function getValueOfDay(dateStr = new Date().toISOString().slice(0, 10)) {
  const values = listValues();
  if (values.length === 0) return null;
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) >>> 0;
  }
  return { date: dateStr, value: values[hash % values.length] };
}

/**
 * Strong value-name match for the search box, e.g.:
 *   "أحاديث الصدق" -> sidq, "hadith about patience" -> sabr, "الرحمة" -> rahmah
 * Returns the value meta or null. Intentionally conservative.
 */
export function matchValueByName(query) {
  const doc = loadDoc();
  if (!doc.values.length || !query) return null;
  const q = String(query).trim().toLowerCase();
  const qAr = normalizeArabic(String(query));

  for (const v of doc.values) {
    const nameAr = normalizeArabic(v.nameAr);
    const nameArBare = nameAr.replace(/^ال/, '');
    const nameEn = v.nameEn.toLowerCase();
    const nameEnBare = nameEn.replace(/^(the|a)\s/, '');

    const arHit = nameAr.length >= 3 && (qAr === nameAr || qAr.includes(nameAr) ||
      (nameArBare.length >= 4 && new RegExp(`(^|\\s)${escapeRegex(nameArBare)}($|\\s)`).test(qAr)));
    const enHit = nameEn.length >= 4 && (q === nameEn || q.includes(nameEn) ||
      new RegExp(`\\b${escapeRegex(nameEnBare)}\\b`).test(q));

    if (arHit || enHit) {
      return { id: v.id, nameAr: v.nameAr, nameEn: v.nameEn, iconKey: v.iconKey, accent: v.accent, count: (v.hadithIds || []).length };
    }
  }
  return null;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
